change push flow

diff --git a/.github/workflows/add_new_or_updated_feeds.yml b/.github/workflows/add_new_or_updated_feeds.yml
--- a/.github/workflows/add_new_or_updated_feeds.yml
+++ b/.github/workflows/add_new_or_updated_feeds.yml
@@ -66,8 +66,8 @@ jobs:
         run: |
             git pull
             git checkout -b ${{ steps.create_branch_name.outputs.BRANCH }}
-            git reset --hard ${{ env.BASE }}
-            git clean -df
+            # git reset --hard ${{ env.BASE }}
+            # git clean -df
 
       - name: Download CSV and process each lines
         id: process-csv
@@ -137,7 +137,7 @@ jobs:
           # git fetch origin main
 
           # Create or reset the branch to the current main
-          git checkout -B "$BRANCH_NAME"
+          git checkout "$BRANCH_NAME"
 
           # Configure git
           # git config --global user.name "${{ env.USERNAME }}"
@@ -157,7 +157,7 @@ jobs:
           git commit -m "Automated commit — New/Updated feed(s)"
           
           echo "Force push changes to the branch"
-          git push -u origin "$BRANCH_NAME" || (echo "Git push failed!" && git remote -v && git branch -vv && exit 1)
+          git push origin HEAD || (echo "Git push failed!" && git remote -v && git branch -vv && exit 1)
           
           echo "Check if a PR already exists"
           EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number')
