test awk

diff --git a/.github/workflows/add_new_or_updated_feeds.yml b/.github/workflows/add_new_or_updated_feeds.yml
--- a/.github/workflows/add_new_or_updated_feeds.yml
+++ b/.github/workflows/add_new_or_updated_feeds.yml
@@ -130,27 +130,27 @@ jobs:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         shell: bash
 
-      - name: Ensure grep is installed
-        run: |
-          echo "Checking if grep is installed..."
+      # - name: Ensure grep is installed
+      #   run: |
+      #     echo "Checking if grep is installed..."
           
-          if ! command -v grep &> /dev/null; then
-            echo "Error: grep is not installed! Attempting to install..."
+      #     if ! command -v grep &> /dev/null; then
+      #       echo "Error: grep is not installed! Attempting to install..."
             
-            # Install grep on Ubuntu
-            sudo apt-get update && sudo apt-get install -y grep
+      #       # Install grep on Ubuntu
+      #       sudo apt-get update && sudo apt-get install -y grep
 
-            # Verify installation
-            if ! command -v grep &> /dev/null; then
-              echo "Installation failed. grep is still missing!"
-              exit 1
-            else
-              echo "grep installed successfully ✅"
-            fi
-          else
-            echo "grep is already installed ✅"
-          fi
-        shell: bash
+      #       # Verify installation
+      #       if ! command -v grep &> /dev/null; then
+      #         echo "Installation failed. grep is still missing!"
+      #         exit 1
+      #       else
+      #         echo "grep installed successfully ✅"
+      #       fi
+      #     else
+      #       echo "grep is already installed ✅"
+      #     fi
+      #   shell: bash
 
 
       - name: Commit, push, and create PR
@@ -191,8 +191,8 @@ jobs:
           echo "----------"
 
           echo "Count new files"
-          NEW_FILE_COUNT=$(git status --porcelain | grep -c "^A")
-          # NEW_FILE_COUNT=$(git status --porcelain | awk '$1 == "A" {count++} END {print count+0}')
+          # NEW_FILE_COUNT=$(git status --porcelain | grep -c "^A")
+          NEW_FILE_COUNT=$(git status --porcelain | awk '$1 == "A" {count++} END {print count+0}')
           echo "----------"
 
           echo "Commit changes: $NEW_FILE_COUNT"
