change push command

diff --git a/.github/workflows/add_new_or_updated_feeds.yml b/.github/workflows/add_new_or_updated_feeds.yml
--- a/.github/workflows/add_new_or_updated_feeds.yml
+++ b/.github/workflows/add_new_or_updated_feeds.yml
@@ -157,7 +157,7 @@ jobs:
           git commit -m "Automated commit — New/Updated feed(s)"
           
           echo "Force push changes to the branch"
-          git push -f origin "$BRANCH_NAME" || (echo "Git push failed!" && git remote -v && git branch -vv && exit 1)
+          git push -u origin "$BRANCH_NAME" || (echo "Git push failed!" && git remote -v && git branch -vv && exit 1)
           
           echo "Check if a PR already exists"
           EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number')
@@ -226,7 +226,7 @@ jobs:
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
 
       - name: Post notification in Slack in case of failure
-        if: failure()
+        # if: failure()
         uses: slackapi/slack-github-action@v1.26.0
         with:
           payload: |
